
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Program Files/JetBrains/CLion 2024.2.2/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        C:/Users/natan/OneDrive/Documentos/Universidade Católica de Brasília/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/3.31.6/CompilerIdC/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/natan/OneDrive/Documentos/Universidade Cat\u00f3lica de Bras\u00edlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cj3hua"
      binary: "C:/Users/natan/OneDrive/Documentos/Universidade Cat\u00f3lica de Bras\u00edlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cj3hua"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/natan/OneDrive/Documentos/Universidade Católica de Brasília/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cj3hua'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 "C:/PROGRA~1/JetBrains/CLion 2024.2.2/bin/mingw/bin/mingw32-make.exe" -f Makefile cmTC_811b5/fast
        C:/PROGRA~1/JetBrains/CLion 2024.2.2/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_811b5.dir\\build.make CMakeFiles/cmTC_811b5.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/natan/OneDrive/Documentos/Universidade Cat¾lica de BrasÝlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cj3hua'
        mingw32-make[1]: CMakeFiles\\cmTC_811b5.dir\\build.make: No such file or directory
        mingw32-make[1]: *** No rule to make target 'CMakeFiles\\cmTC_811b5.dir\\build.make'.  Stop.
        mingw32-make[1]: Leaving directory 'C:/Users/natan/OneDrive/Documentos/Universidade Cat¾lica de BrasÝlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-cj3hua'
        mingw32-make: *** [Makefile:133: cmTC_811b5/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/share/cmake-3.31/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Program Files/JetBrains/CLion 2024.2.2/bin/mingw/bin/gcc.exe"
    directories:
      source: "C:/Users/natan/OneDrive/Documentos/Universidade Cat\u00f3lica de Bras\u00edlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ud7dc0"
      binary: "C:/Users/natan/OneDrive/Documentos/Universidade Cat\u00f3lica de Bras\u00edlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ud7dc0"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/natan/OneDrive/Documentos/Universidade Católica de Brasília/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ud7dc0'
        
        Run Build Command(s): "C:/Program Files/JetBrains/CLion 2024.2.2/bin/cmake/win/x64/bin/cmake.exe" -E env VERBOSE=1 "C:/PROGRA~1/JetBrains/CLion 2024.2.2/bin/mingw/bin/mingw32-make.exe" -f Makefile cmTC_34222/fast
        C:/PROGRA~1/JetBrains/CLion 2024.2.2/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_34222.dir\\build.make CMakeFiles/cmTC_34222.dir/build
        mingw32-make[1]: Entering directory 'C:/Users/natan/OneDrive/Documentos/Universidade Cat¾lica de BrasÝlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ud7dc0'
        mingw32-make[1]: CMakeFiles\\cmTC_34222.dir\\build.make: No such file or directory
        mingw32-make[1]: *** No rule to make target 'CMakeFiles\\cmTC_34222.dir\\build.make'.  Stop.
        mingw32-make[1]: Leaving directory 'C:/Users/natan/OneDrive/Documentos/Universidade Cat¾lica de BrasÝlia/UCB/Semestre 02/01-25 - Estrutura de Dados/Trabalho_bilheteria/SistemaBilheteria_finalversionNatanael/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ud7dc0'
        mingw32-make: *** [Makefile:133: cmTC_34222/fast] Error 2
        
      exitCode: 2
...
